const countries = {
  argentina: 'AR',
  australia: 'AU',
  austria: 'AT',
  belgium: 'BE',
  brazil: 'BR',
  canada: 'CA',
  chile: 'CL',
  denmark: 'DK',
  finland: 'FI',
  france: 'FR',
  germany: 'DE',
  'hong kong sar': 'HK',
  'hong kong': 'HK',
  india: 'IN',
  indonesia: 'ID',
  italy: 'IT',
  japan: 'JP',
  korea: 'KR',
  malaysia: 'MY',
  mexico: 'MX',
  netherlands: 'NL',
  'new zealand': 'NZ',
  norway: 'NO',
  "people's republic of china": 'CN',
  'peoples republic of china': 'CN',
  china: 'CN',
  poland: 'PL',
  portugal: 'PT',
  'republic of the philippines': 'PH',
  philippines: 'PH',
  russia:	'RU',
  'saudi arabia': 'SA',
  'south africa': 'ZA',
  spain: 'ES',
  sweden: 'SE',
  switzerland: 'CH',
  taiwan: 'TW',
  turkey: 'TR',
  'united kingdom': 'GB',
  'united states': 'US',
  ukraine: 'UA'
};

module.exports = {
  countries
};
